# command
uint8 ADD_WITHOUT_NAME = 0
uint8 ADD_WITH_NAME = 1
uint8 REMOVE = 2

uint8 command
# float32 radius
string name
---
bool result
# string[] other_name
# string[] added_spot
# string[] removed_spot
---
